// <auto-generated />
using Handmade.Service.EmbroideryAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Handmade.Service.EmbroideryAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230127200841_BDDEMB")]
    partial class BDDEMB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Handmade.Service.EmbroideryAPI.Models.Embroidery", b =>
                {
                    b.Property<int>("EmbroideryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmbroideryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbroideryName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("EmbroideryId");

                    b.ToTable("Embroideries");

                    b.HasData(
                        new
                        {
                            EmbroideryId = 1,
                            CategoryName = "categorie1",
                            EmbroideryName = "ChaiseBoisMassif",
                            ImageURL = "1.jpg",
                            Price = 15.0
                        },
                        new
                        {
                            EmbroideryId = 2,
                            CategoryName = "categorie1",
                            EmbroideryName = "ChaiseBoisMassif",
                            ImageURL = "1.jpg",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
